### ISSUE TITLE
Vagrat script creates 2VM or Just One?

### ISSUE THREAD

**Issue by alokprasad** [haggaie/rdma-experiment#6]
Is the Vagrant Script create 2 VM or Just one?
It would be nice if actually 2 VM are created for better understanding of IB verb programming

**Comment by haggaie** [comment]
I originally wrote it for 2 VMs, but the changed it to one. The reason was that it should be easier for students to run on their laptop, and you can still run two RDMA process on the same VM, communicating through loopback.

You can take a look at the original code before this patch: https://github.com/haggaie/rdma-experiment/commit/6f9ebd9cb7e2cc2abda85c78eb9c5ec063f1e3e9 and play with it yourself.

**Comment by alokprasad** [comment]
@haggaie Thanks , Actually if students want to use QP1/GSI for initial connection setup will it work in loop back environment ? Two VM i think is still be better to understand some intricacies on initial connection establishment .
Anyway nice work on creating this repo.

**Comment by haggaie** [comment]
Thanks.

The example code uses rdmacm with QP1, and it should work with loopback as well (not sure about using the loopback interface IP address, but if you use a RoCE device's IP address it should work with loopback).
